### ISSUE TITLE
FashionIQ datasets

### ISSUE THREAD

**Issue by develop-productivity** [Monoxide-Chen/uncertainty_retrieval#2]
The FashionIQ dataset has a lot of broken urls and it can't be download in the google grive you provided, can you provide a copy of the dataset from google drive again? It can be  or Baidu network disk, or you can contact me by email

**Comment by Monoxide-Chen** [comment]
I have checked google drive that the download link is valid. I upload fashionIQ to another [google drive](https://drive.google.com/file/d/1K8ZMx7BXS1Xbe5GgUzbpYw08sfTEVi5O/view?usp=sharing) that may help you to download it.

**Comment by develop-productivity** [comment]
> I have checked google drive that the download link is valid. I upload fashionIQ to another [google drive](https://drive.google.com/file/d/1K8ZMx7BXS1Xbe5GgUzbpYw08sfTEVi5O/view?usp=sharing) that may help you to download it.

Thanks a lot!
