### ISSUE TITLE
About Fashion200K dataset

### ISSUE THREAD

**Issue by HaoliangZhou** [Monoxide-Chen/uncertainty_retrieval#4]
Thanks for your time!
The training set of Fashion200k dataset is to get 'source_img', 'target_img', 'mod_text' for training, but the test sets of many projects are separate, for example, using def 'get_test_queries' to get 29,789 query, which contains 'source_img' and 'mod_text', as well as the 's_img_caption' and 't_img_caption', but I would like to ask how to get the 'target_img', so as to get the complete ternary for test.

**Comment by Monoxide-Chen** [comment]
Yes, the Fashion200k dataset does not directly provide the query triples. The target images and reference images are separated at this line in the code: https://github.com/Monoxide-Chen/uncertainty_retrieval/blob/f1fd8286f3b203842c9957de94624fcee699f20d/data/fashion200k.py#L166. The dataset processing code is inherited from CosMo, and we did not modify it.

**Comment by HaoliangZhou** [comment]
Thanks a lot! May I have your e-mail, please?

**Comment by Monoxide-Chen** [comment]
Sure! My email is monoxidechen@gmail.com
